// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quản_lý_công_tơ_điện.Models;

public partial class Bienbancapdien
{
    public string MaBienBan { get; set; }

    public DateTime NgayLap { get; set; }

    public DateTime? ThoiGianBatDauCapDien { get; set; }

    public int? ChiSoBanDau { get; set; }

    public string ViTriLapDat { get; set; }

    public string MaCongTo { get; set; }

    public string HangSanXuat { get; set; }

    public int? NamSanXuat { get; set; }

    public string MaPhieu { get; set; }

    public string MaLoaiCongTo { get; set; }

    public virtual Loaicongto MaLoaiCongToNavigation { get; set; }

    public virtual Phieucapdien MaPhieuNavigation { get; set; }
}