// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quản_lý_công_tơ_điện.Models;

public partial class Cauhinhcapdien
{
    public string MaMucDich { get; set; }

    public string MaSoPha { get; set; }

    public virtual Mucdich MaMucDichNavigation { get; set; }

    public virtual Loaipha MaSoPhaNavigation { get; set; }

    public virtual ICollection<Phieucapdien> Phieucapdiens { get; set; } = new List<Phieucapdien>();
}