// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quản_lý_công_tơ_điện.Models;

public partial class Loaicongto
{
    public string MaLoaiCongTo { get; set; }

    public string TenLoaiCongTo { get; set; }

    public virtual ICollection<Bienbancapdien> Bienbancapdiens { get; set; } = new List<Bienbancapdien>();

    public virtual ICollection<Cauhinhcongto> Cauhinhcongtos { get; set; } = new List<Cauhinhcongto>();
}