// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quản_lý_công_tơ_điện.Models;

public partial class Mucdich
{
    public string MaMucDich { get; set; }

    public string TenMucDich { get; set; }

    public virtual ICollection<Cauhinhcapdien> Cauhinhcapdiens { get; set; } = new List<Cauhinhcapdien>();
}