// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Quản_lý_công_tơ_điện.Models;

public partial class Phieucapdien
{
    public string MaPhieu { get; set; }

    public DateTime ThoiGianGui { get; set; }

    public string HoTen { get; set; }

    public string Cccd { get; set; }

    public DateOnly? NamSinh { get; set; }

    public string SoDienThoai { get; set; }

    public string Email { get; set; }

    public string DiaChi { get; set; }

    public string MaMucDich { get; set; }

    public string MaSoPha { get; set; }

    public string TrangThai { get; set; } = "Chưa xử lý";

    public virtual Bienbancapdien Bienbancapdien { get; set; }

    public virtual Cauhinhcapdien Cauhinhcapdien { get; set; }
}