// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Quản_lý_công_tơ_điện.Models;

public partial class QuanLyCapDienContext : DbContext
{
    public QuanLyCapDienContext(DbContextOptions<QuanLyCapDienContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bienbancapdien> Bienbancapdiens { get; set; }

    public virtual DbSet<Cauhinhcapdien> Cauhinhcapdiens { get; set; }

    public virtual DbSet<Loaicongto> Loaicongtos { get; set; }

    public virtual DbSet<Loaipha> Loaiphas { get; set; }

    public virtual DbSet<Mucdich> Mucdiches { get; set; }

    public virtual DbSet<Phieucapdien> Phieucapdiens { get; set; }

    public virtual DbSet<Cauhinhcongto> Cauhinhcongtos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bienbancapdien>(entity =>
        {
            entity.HasKey(e => e.MaBienBan);

            entity.ToTable("BIENBANCAPDIEN");

            entity.HasIndex(e => e.MaPhieu, "UQ_BIENBANCAPDIEN_MaPhieu").IsUnique();

            entity.Property(e => e.MaBienBan).HasMaxLength(20);
            entity.Property(e => e.HangSanXuat).HasMaxLength(100);
            entity.Property(e => e.MaCongTo).HasMaxLength(50);
            entity.Property(e => e.MaLoaiCongTo)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.MaPhieu)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.NgayLap)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ThoiGianBatDauCapDien).HasColumnType("datetime");
            entity.Property(e => e.ViTriLapDat).HasMaxLength(255);

            entity.HasOne(d => d.MaLoaiCongToNavigation).WithMany(p => p.Bienbancapdiens)
                .HasForeignKey(d => d.MaLoaiCongTo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BIENBANCAPDIEN_LOAICONGTO");

            entity.HasOne(d => d.MaPhieuNavigation).WithOne(p => p.Bienbancapdien)
                .HasForeignKey<Bienbancapdien>(d => d.MaPhieu)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BIENBANCAPDIEN_PHIEUCAPDIEN");
        });

        modelBuilder.Entity<Cauhinhcapdien>(entity =>
        {
            entity.HasKey(e => new { e.MaMucDich, e.MaSoPha });

            entity.ToTable("CAUHINHCAPDIEN");

            entity.Property(e => e.MaMucDich).HasMaxLength(20);
            entity.Property(e => e.MaSoPha).HasMaxLength(20);

            entity.HasOne(d => d.MaMucDichNavigation).WithMany(p => p.Cauhinhcapdiens)
                .HasForeignKey(d => d.MaMucDich)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CAUHINHCAPDIEN_MUCDICH");

            entity.HasOne(d => d.MaSoPhaNavigation).WithMany(p => p.Cauhinhcapdiens)
                .HasForeignKey(d => d.MaSoPha)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CAUHINHCAPDIEN_LOAIPHA");
        });

        modelBuilder.Entity<Loaicongto>(entity =>
        {
            entity.HasKey(e => e.MaLoaiCongTo);

            entity.ToTable("LOAICONGTO");

            entity.Property(e => e.MaLoaiCongTo).HasMaxLength(20);
            entity.Property(e => e.TenLoaiCongTo)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Loaipha>(entity =>
        {
            entity.HasKey(e => e.MaSoPha);

            entity.ToTable("LOAIPHA");

            entity.Property(e => e.MaSoPha).HasMaxLength(20);
            entity.Property(e => e.TenSoPha)
                .IsRequired()
                .HasMaxLength(100);

        });

        modelBuilder.Entity<Mucdich>(entity =>
        {
            entity.HasKey(e => e.MaMucDich);

            entity.ToTable("MUCDICH");

            entity.Property(e => e.MaMucDich).HasMaxLength(20);
            entity.Property(e => e.TenMucDich)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Phieucapdien>(entity =>
        {
            entity.HasKey(e => e.MaPhieu);

            entity.ToTable("PHIEUCAPDIEN");

            entity.Property(e => e.MaPhieu).HasMaxLength(20);
            entity.Property(e => e.Cccd)
                .IsRequired()
                .HasMaxLength(12)
                .HasColumnName("CCCD");
            entity.Property(e => e.DiaChi)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.HoTen)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.MaMucDich)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.MaSoPha)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.SoDienThoai).HasMaxLength(15);
            entity.Property(e => e.ThoiGianGui)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TrangThai)
                .HasMaxLength(100)
                .IsRequired()
                .HasDefaultValue("Chưa xử lý");

            entity.HasOne(d => d.Cauhinhcapdien).WithMany(p => p.Phieucapdiens)
                .HasForeignKey(d => new { d.MaMucDich, d.MaSoPha })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEUCAPDIEN_CAUHINHCAPDIEN");
        });

        modelBuilder.Entity<Cauhinhcongto>(entity =>
        {
            // 1. THIS LINE FIXES YOUR CRASH! It tells EF Core what the Primary Key is.
            entity.HasKey(e => new { e.MaSoPha, e.MaLoaiCongTo });

            // 2. Point it to the SQL table
            entity.ToTable("CAUHINHCONGTO");

            // 3. Wire up the Foreign Key to LOAICONGTO
            entity.HasOne(d => d.MaLoaiCongToNavigation)
                  .WithMany(p => p.Cauhinhcongtos)
                  .HasForeignKey(d => d.MaLoaiCongTo)
                  .OnDelete(DeleteBehavior.ClientSetNull)
                  .HasConstraintName("FK_CAUHINHCONGTO_LOAICONGTO");

            // 4. Wire up the Foreign Key to LOAIPHA
            entity.HasOne(d => d.MaSoPhaNavigation)
                  .WithMany(p => p.Cauhinhcongtos)
                  .HasForeignKey(d => d.MaSoPha)
                  .OnDelete(DeleteBehavior.ClientSetNull)
                  .HasConstraintName("FK_CAUHINHCONGTO_LOAIPHA");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}